// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnVEoSt-6KmLeOAojIPPbNjLAta_9n2BU',
    appId: '1:381690222292:web:c39f16eded9b16e47d8d41',
    messagingSenderId: '381690222292',
    projectId: 'katakata-daniel',
    authDomain: 'katakata-daniel.firebaseapp.com',
    storageBucket: 'katakata-daniel.firebasestorage.app',
    measurementId: 'G-68MTBLT8KN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-AQRei42zKMZNurafoPNNB_62nJ5Uxd0',
    appId: '1:381690222292:android:d6cd200003a18cd37d8d41',
    messagingSenderId: '381690222292',
    projectId: 'katakata-daniel',
    storageBucket: 'katakata-daniel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLliD35RGcv3wt9OdNwSAKl1rs0AUp4G8',
    appId: '1:381690222292:ios:2bd81eafef3e02a17d8d41',
    messagingSenderId: '381690222292',
    projectId: 'katakata-daniel',
    storageBucket: 'katakata-daniel.firebasestorage.app',
    iosBundleId: 'com.example.katakata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLliD35RGcv3wt9OdNwSAKl1rs0AUp4G8',
    appId: '1:381690222292:ios:2bd81eafef3e02a17d8d41',
    messagingSenderId: '381690222292',
    projectId: 'katakata-daniel',
    storageBucket: 'katakata-daniel.firebasestorage.app',
    iosBundleId: 'com.example.katakata',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnVEoSt-6KmLeOAojIPPbNjLAta_9n2BU',
    appId: '1:381690222292:web:afd4467a520c2d377d8d41',
    messagingSenderId: '381690222292',
    projectId: 'katakata-daniel',
    authDomain: 'katakata-daniel.firebaseapp.com',
    storageBucket: 'katakata-daniel.firebasestorage.app',
    measurementId: 'G-Q5K1NMT8S2',
  );
}
